### ISSUE TITLE
Setup Bash Script is broken for Fedora

### ISSUE THREAD

**Issue by devGregA** [rackerlabs/django-DefectDojo#12]
Hey guys, it looks the the bash script was broken (for Fedora and probably RHEL) when we were working on the robustness.
Originally it would also perform a go to fail when an error occurred. I'll look into it, but if you have any insight Charles it would be helpful.

UPDATE 2. I'm not sure what is wrong here now. I'm not sure what egg its referring to. Will investigate when I can. I'm going to rerun on a debian box to see if it is also broken

DUMP 2:

Traceback (most recent call last):
  File "setup.py", line 30, in <module>
    url='https://github.com/rackerlabs/django-DefectDojo'
  File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 73, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 101, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 358, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 574, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 625, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 671, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 572, in resolve
    requirements.extend(dist.requires(req.extras)[::-1])
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2240, in requires
    dm = self._dep_map
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2225, in _dep_map
    for extra,reqs in split_sections(self._get_metadata(name)):
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2666, in split_sections
    for line in yield_lines(s):
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1926, in yield_lines
    for ss in strs:
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2254, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1316, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1308, in get_metadata
    return self._get(self._fn(self.egg_info,name))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1372, in _get
    return self.loader.get_data(path)
zlib.error: Error -5 while decompressing data: incomplete or truncated stream
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management

UPDATE 1 submitted a PR & merged for bellow issue.

Now I'm hitting a snag with tastypie. Gotofail is still broken.

dump2: 
Reading https://pypi.python.org/simple/django-tastypie-swagger/
No local packages or download links found for django-tastypie-swagger>=0.1.3
error: Could not find suitable distribution for Requirement.parse('django-tastypie-swagger>=0.1.3')
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management

beginning dump:

Created database trackerdb.
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from setuptools import setup
ImportError: No module named setuptools
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
==============================================================================

SUCCESS! Now edit your settings.py file in the 'dojo' directory to complete the installation.

When you're ready to start the DefectDojo server, type 'python manage.py runserver' in this directory.

**Comment by grendel513** [comment]
Added the appropriate pip path for v0.1.3, give it a whirl and let me know.

**Comment by grendel513** [comment]
This has to do with your python path: see http://stackoverflow.com/questions/312549/no-module-named-django-core

**Comment by devGregA** [comment]
Looks like the 1.7 update also broke the debian install. Not sure if we want to roll back, we may also want to consider rolling back to the original bash script until we can work the bugs out of this one

**Comment by grendel513** [comment]
I don't think it has to do with the Django 1.7 upgrade. I ran the setup.bash scripts on both the pythonanywhere server and on a Kali virtual box on my local machine.  It worked on both...but I did have to remove the Pillow requirement (besides we dont use PIL, I have no idea why it is there)

**Comment by grendel513** [comment]
I did notice that the packages you install are different from each OS:

if [[ ! -z $YUM_CMD ]]; then
	sudo yum install gcc libmysqlclient-dev python-devel mysql-server mysql-devel mysql-python python-setuptools -y
elif [[ ! -z $APT_GET_CMD ]]; then
    sudo apt-get install gcc libssl-dev python-dev libmysqlclient-dev python-pip mysql-server -y


setuptools is only present for one package manager.

**Comment by grendel513** [comment]
I think the problem is "Django 1.7 requires Python 2.7 or above" see https://docs.djangoproject.com/fr/1.7/releases/1.7/ for details.  We should recommend a virtualenv?
